# Generated by Django 3.1.7 on 2021-03-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRetrieval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(default='SOME STRING', max_length=140)),
                ('number_of_image_to_search', models.IntegerField()),
                ('number_of_result', models.IntegerField()),
            ],
        ),
    ]
